### ISSUE TITLE
An internal error

### ISSUE THREAD

**Issue by RispyCZ** [Qballl/WildernessTp#30] opened 2018-12-11 17:00 UTC
Hello,

I have problem with this plugin. If I set up something using gui or in config it show this error message.

Log: https://pastebin.com/Ce41wkt5
My config: https://pastebin.com/0CvPzi7T (setup by GUI)

**Comment by Qballl** [comment] 2018-12-11 18:10
Oh I know what the issue is. WorldGuard updated again and I had not yet posted an update with an updated version of the wrapper. Try this one and tell me if it works https://github.com/Qballl/WildernessTp/raw/master/target/WildTp.jar

**Comment by Qballl** [comment] 2019-01-17 00:46
Fixed closing

**Closed as completed by Qballl** 2019-01-17 00:46 UTC
